name: Build Kernel Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t kernel-module-builder .

      - name: Build kernel module
        run: |
          docker run --rm -v ${{ github.workspace }}:/src kernel-module-builder

